language: r
cache: packages
services:
  - docker

notifications:
  email:
    - sebastian.warnholz@inwt-statistics-de

after_success:
  - Rscript -e 'covr::codecov()'
  - test $TRAVIS_PULL_REQUEST == "false" &&
    test $TRAVIS_BRANCH == "master" &&
    bash deploy.sh
