language: r
cache: packages
before_install:
  - pip install awscli
services:
  - docker
notifications:
  email:
  - sebastian.warnholz@inwt-statistics-de
after_success:
  - Rscript -e 'covr::codecov()'
  - test $TRAVIS_PULL_REQUEST == "false" &&
    test $TRAVIS_BRANCH == "master" &&
    curl https://raw.githubusercontent.com/INWTlab/drat/main/deploy.sh > deploy.sh &&
    bash deploy.sh
env:
  global:
  - secure: Bbp20988uDm5AsRHtsqTk4kpnRd8tdADHylaLcXMw6DkHLAhNBPQTFpLtgzjn7fnkWyfwH0tyZf4TeEy7RSTTz+rEy5yUEfVXLW0dpHI/GacHDQO2PnKfOUZK6PFDatl6Vq5o6h2xCNbvZtwrkpJnsBm4ergKTjg+9Jq3lbgukkKP1ZVrYAcRgvRXHC8dTVci6pmNRwGer+QktPWA0zMfrmKcv40XvHHDX75ifqu4JbEVHALt9ZQ5yCa1i6NfoMBjENCfUb77wdIxiv3/k2tW5IAqAZbNWCg0HUuSbhXTQkvCJqHc1+OaML1hcFI7TTDZ2+mbKxlm3B2OF0SY4A48xIKdk9PbZjYkboNLoOvqJUFiHdrote7rZYYkM0+r6Kn/PbdN8B4LzpaSY1yC/m4YM4P8wGEtj9Zkd8Yl/oDvmxtfFnmY2KDjVOlpDnRkTwyLJUyGdpiS3kdxf93EisbW4Nri1zF4mJUi3py8/DfS8JtGOIre7Pv5h4nFEmDkeawvLbrBIY4WzWo2COVOp6j/ksKdC5EI/IaoeDdLl7qwjkbU6yBcSv644/UsVGYAwV+twDVSjCIngWcgFHW0qxkgrKoDciUTqUzEvMNbEC9xkoBYNX9zEX9oh+T2ijyyfcXmLBtKP86SoovqIZhxQmE6jddSqDWsCevtW1m/+9orXQ=
