name: R-CMD-check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: # run workflow manually

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and test
        run: |
          docker build -t test-build . && docker run test-build
